// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDORrdIQgJ80ky1CmhxRqXIQuZtLmHT1wk',
    appId: '1:406150939556:web:c0f201829aeac55f7a3731',
    messagingSenderId: '406150939556',
    projectId: 'res-q-93ca6',
    authDomain: 'res-q-93ca6.firebaseapp.com',
    storageBucket: 'res-q-93ca6.firebasestorage.app',
    measurementId: 'G-CWQ5QWMFP6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyACxwGPNAAb9lptJ-6vOIJl16dWPx9Df80',
    appId: '1:406150939556:android:040fbee0a77df46c7a3731',
    messagingSenderId: '406150939556',
    projectId: 'res-q-93ca6',
    storageBucket: 'res-q-93ca6.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBhx_BPZ73Yr3bMQJITe649APIlfyRo-iY',
    appId: '1:406150939556:ios:17b16b57f74e52b07a3731',
    messagingSenderId: '406150939556',
    projectId: 'res-q-93ca6',
    storageBucket: 'res-q-93ca6.firebasestorage.app',
    iosBundleId: 'com.example.resq',
  );
}
